sdk:
    finding:
        request_class: FindingAPI\Core\Request\Request
        api_class: FindingAPI\Finding
        request_validators: [FindingAPI\Core\Request\ItemFiltersValidator]
        listeners:
            request_pre_process:
                class: FindingAPI\Core\Listener\ValidateItemFiltersListener
                method: onPreProcessRequest
            add_processor:
                class: FindingAPI\Core\Listener\AddProcessorListener
                method: onAddProcessor
            pre_send_request:
                class: FindingAPI\Core\Listener\PreSendRequestListener
                method: onPreSendRequest
        global_parameters:
            ebay_url:
                representation: null
                value: http://svcs.ebay.com/services/search/FindingService/v1
                type: [required, standalone]
                valid: null
            # string that will be saved as the name of the parameter
            security_appname:
                # string that will be in the url
                representation: SECURITY-APPNAME
                # value that will be appended as the value in the query part of the url
                value: Mariokrl-testing-PRD-ee6e68035-e73c8a53
                # valid types: required, optional, injectable, standalone. has to be an array and can have multiple values
                # a type cannot be required and optional at the same time
                # if required, then 'value' has to be present and parameter construction
                # if value is injectable and required, then it has to be present on application runtime
                type: [required]
                # valid values for this option. has corelation with 'value' option
                valid: null
                # is the parameter deprecated or not
                deprecated: false
                # if the parameter is deprecated, then user can choose whether its usage will throw an exception or not
                throws_exception_if_deprecated: false
                # if obsolite is set to true, then usage of this parameter will always throw an exception no matter what value
                # is set on 'deprecated' option
                obsolete: false
                # the message of the exception for obsolete or deprecated
                error_message: 'Invalid value for %s and represented as %s'
            operation_name:
                representation: OPERATION-NAME
                value: null
                type: [injectable, required]
                valid: [findItemsByKeywords, findItemsByCategory, findItemsAdvanced, findCompletedItems, findItemsByProduct, findItemsIneBayStores, getHistograms, getSearchKeywordsRecommendation, getVersion]
            service_version:
                representation: SERVICE-VERSION
                value: 1.3.0
                type: [injectable, required]
                valid: [1.3.0]
            response_data_format:
                representation: RESPONSE-DATA-FORMAT
                value: xml
                valid: [xml, json]
                type: [required]
            global_id:
                representation: GLOBAL-ID
                value: EBAY-US
                type: [injectable, required]
                valid: [EBAY-US, EBAY-ENCA, EBAY-GB, EBAY-AU, EBAY-AT, EBAY-FRBE, EBAY-FR, EBAY-DE, EBAY-MOTOR, EBAY-IT, EBAY-NLBE, EBAY-NL, EBAY-ES, EBAY-CH, EBAY-HK, EBAY-IN, EBAY-IE, EBAY-MY, EBAY-FRCA, EBAY-PH, EBAY-PL, EBAY-SG]

        special_parameters:
            keywords:
                representation: keywords
                value: null
                type: [optional]
                valid: null
            category_id:
                representation: categoryId
                value: null
                type: [optional]
                valid: null
                error_message: '%s is obsolete and cannot be used anymore. Represented by %s'
            description_search:
                representation: descriptionSearch
                value: null
                type: [optional]
                valid: null
            product_id_type:
                representation: 'productId.@type'
                value: null
                type: [optional]
                valid: [ReferenceID, ISBN, UPC, EAN]
            product_id:
                representation: productId
                value: null
                type: [optional]
                valid: null
            store_name:
                representation: storeName
                value: null
                type: [optional]
                valid: null

        methods:
            valid_methods: operation_name
            metadata:
                find_items_by_keywords:
                    name: findItemsByKeywords
                    object: FindingAPI\Core\Request\Method\FindItemsByKeywords
                    methods: [keywords]
                find_items_by_category:
                    name: findItemsByCategory
                    object: FindingAPI\Core\Request\Method\FindItemsByCategory
                    methods: [category_id]
                find_items_advanced:
                    name: findItemsAdvanced
                    object: FindingAPI\Core\Request\Method\FindItemsAdvanced
                    methods: [keywords, category_id, description_search]
                find_completed_items:
                    name: findCompletedItems
                    object: FindingAPI\Core\Request\Method\FindCompletedItems
                    methods: [keywords, category_id]
                find_items_by_product:
                    name: findItemsByProduct
                    object: FindingAPI\Core\Request\Method\FindItemsByProduct
                    methods: [product_id_type, product_id]
                find_items_in_ebay_stores:
                    name: findItemsIneBayStores
                    object: FindingAPI\Core\Request\Method\FindItemsByProduct
                    methods: [store_name]
                get_histograms:
                    name: getHistograms
                    object: FindingAPI\Core\Request\Method\GetHistograms
                    methods: [category_id]
                get_search_keywords_recommendations:
                    name: getSearchKeywordsRecommendation
                    object: FindingAPI\Core\Request\Method\GetSearchKeywordsRecommendations
                    methods: [keywords]
                get_version:
                    name: getVersion
                    object: FindingAPI\Core\Request\Method\GetVersion
                    methods: []
